sudo: required
language: java
dist: trusty
jdk: oraclejdk8
python:
  - 3.8
  
addons:
  sonarcloud:
    organization: "notification-system"
    token: $SONAR_TOKEN

before_install:
#   - sudo apt-get install build-essential checkinstall
#   - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
   - sudo add-apt-repository -y ppa:deadsnakes/ppa
   - sudo apt-get update
   - sudo apt install python3.8
   - python3.8 -V
   - pip -V
   - python3.8 -m pip3 install awscli
script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - ./mvnw clean install -B
  - mvn clean verify sonar:sonar -Pcoverage 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
services:
  - docker

after_success:
  - export PATH=$PATH:$HOME/.local/bin 
  - eval $(aws ecr get-login --no-include-email --region eu-north-1)
  - docker build -t covidere .
  - docker tag covidere:latest $AWS_ECR_ACCOUNT.dkr.ecr.eu-north-1.amazonaws.com/shoplokalt:latest
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.eu-north-1.amazonaws.com/shoplokalt:latest
