sudo: required
language: java python
dist: trusty
jdk: oraclejdk8
python:
  - 3.8
  
addons:
  sonarcloud:
    organization: "notification-system"
    token: $SONAR_TOKEN

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - ./mvnw clean install -B
  - mvn clean verify sonar:sonar -Pcoverage 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
services:
  - docker

after_success:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin 
  - eval $(aws ecr get-login --no-include-email --region eu-north-1)
  - docker build -t covidere .
  - docker tag covidere:latest $AWS_ECR_ACCOUNT.dkr.ecr.eu-north-1.amazonaws.com/shoplokalt:latest
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.eu-north-1.amazonaws.com/shoplokalt:latest
